from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Mapping

from tradebot.research.forward_alpha_v25 import canonical_json
from tradebot.research import parameter_neighborhood_ensemble_v61 as evaluation
from tradebot.research import parameter_neighborhood_ensemble_v611 as natural_drift


SCHEMA_VERSION = "6.2-consensus-shrunk-ensemble"
PROTOCOL_PATH = Path("research/V62_CONSENSUS_SHRUNK_ENSEMBLE_PROTOCOL.md")
TRIAL_COUNT = 226

ParameterNeighborhoodV61Error = evaluation.ParameterNeighborhoodV61Error
MemberState = evaluation.MemberState
EnsembleSimulation = evaluation.EnsembleSimulation
MEMBERS = evaluation.MEMBERS
v31 = evaluation.v31
_conservative = evaluation._conservative


def _consensus_target(
    member_targets: Mapping[str, Mapping[str, float]],
) -> dict[str, float]:
    if set(member_targets) != {model.model_id for model in MEMBERS}:
        raise ParameterNeighborhoodV61Error(
            "consensus target requires every frozen member"
        )
    result: dict[str, float] = {}
    member_count = len(MEMBERS)
    for asset in v31.ASSETS:
        weights = [
            float(member_targets[model.model_id].get(asset, 0.0))
            for model in MEMBERS
        ]
        if any(weight < -1e-15 for weight in weights):
            raise ParameterNeighborhoodV61Error(
                "consensus target received a negative member weight"
            )
        mean_weight = sum(weights) / member_count
        agreement = sum(weight > 1e-15 for weight in weights) / member_count
        weight = mean_weight * agreement
        if weight > 1e-15:
            result[asset] = weight
    return result


def simulate_ensemble(
    bars: Mapping[str, Mapping[datetime, Any]],
    features: Mapping[datetime, Mapping[str, v31.Features]],
    cash_returns: Mapping[datetime, float],
    start: datetime,
    end: datetime,
    cost: float,
    *,
    signal_lag_days: int,
) -> EnsembleSimulation:
    if len(MEMBERS) != 16:
        raise ParameterNeighborhoodV61Error(
            "frozen consensus ensemble must contain 16 members"
        )
    if signal_lag_days < 1:
        raise ParameterNeighborhoodV61Error(
            "signal lag must be at least one day"
        )

    states = {model.model_id: MemberState() for model in MEMBERS}
    ensemble_weights: dict[str, float] = {}
    daily_returns: list[float] = []
    cash_daily: list[float] = []
    action_days = 0
    interval_active = False
    interval_strategy_equity = 1.0
    interval_cash_equity = 1.0
    interval_contributions: list[float] = []

    def close_interval() -> None:
        nonlocal interval_active, interval_strategy_equity, interval_cash_equity
        if interval_active:
            interval_contributions.append(
                (interval_strategy_equity - 1.0)
                - (interval_cash_equity - 1.0)
            )
        interval_active = False
        interval_strategy_equity = 1.0
        interval_cash_equity = 1.0

    day = start
    while day <= end:
        signal_day = day - timedelta(days=signal_lag_days)
        next_day = day + timedelta(days=1)
        if signal_day not in features:
            raise ParameterNeighborhoodV61Error(
                f"features unavailable for {v31._utc(signal_day)}"
            )
        cash_return = float(cash_returns[day])
        member_targets: dict[str, dict[str, float]] = {}
        pending_states: dict[str, MemberState] = {}
        any_member_decision = False

        for model in MEMBERS:
            state = states[model.model_id]
            target, selected, sleeve, age, trade_decision = evaluation._member_target(
                model, state, features[signal_day]
            )
            exposure = sum(target.values())
            if trade_decision and exposure > model.maximum_exposure + 1e-12:
                raise ParameterNeighborhoodV61Error(
                    f"new member target cap violated by {model.model_id}"
                )
            if exposure < -1e-12 or exposure >= 1.0:
                raise ParameterNeighborhoodV61Error(
                    f"invalid member exposure for {model.model_id}"
                )
            turnover = sum(
                abs(
                    target.get(asset, 0.0)
                    - state.current_weights.get(asset, 0.0)
                )
                for asset in v31.ASSETS
            )
            if not trade_decision and turnover > 1e-12:
                raise ParameterNeighborhoodV61Error(
                    f"non-due turnover generated by {model.model_id}"
                )
            any_member_decision = any_member_decision or trade_decision
            member_cost = 0.5 * cost * turnover
            pending_states[model.model_id] = MemberState(
                current_weights=evaluation._drift_weights(
                    target, bars, day, next_day, cash_return, member_cost
                ),
                selected_assets=selected,
                sleeve=sleeve,
                age=age,
            )
            member_targets[model.model_id] = target

        target = (
            _consensus_target(member_targets)
            if any_member_decision
            else dict(ensemble_weights)
        )
        exposure = sum(target.values())
        if exposure < -1e-12 or exposure >= 1.0:
            raise ParameterNeighborhoodV61Error(
                "invalid consensus ensemble exposure"
            )
        turnover = sum(
            abs(
                target.get(asset, 0.0)
                - ensemble_weights.get(asset, 0.0)
            )
            for asset in v31.ASSETS
        )
        if not any_member_decision and turnover > 1e-12:
            raise ParameterNeighborhoodV61Error(
                "consensus ensemble generated hidden off-cadence turnover"
            )
        trading_cost = 0.5 * cost * turnover
        action = turnover > 1e-10
        if action:
            close_interval()
            interval_active = True
            action_days += 1

        cash_weight = 1.0 - exposure
        crypto_return = sum(
            weight
            * (
                bars[asset][next_day].open / bars[asset][day].open
                - 1.0
            )
            for asset, weight in target.items()
        )
        net = cash_weight * cash_return + crypto_return - trading_cost
        daily_returns.append(net)
        cash_daily.append(cash_return)
        if interval_active:
            interval_strategy_equity *= 1.0 + net
            interval_cash_equity *= 1.0 + cash_return
        ensemble_weights = evaluation._drift_weights(
            target, bars, day, next_day, cash_return, trading_cost
        )
        states = pending_states
        day += timedelta(days=1)

    final_turnover = sum(ensemble_weights.values())
    if final_turnover > 1e-12:
        final_cost = 0.5 * cost * final_turnover
        daily_returns.append(-final_cost)
        cash_daily.append(0.0)
        action_days += 1
        if not interval_active:
            interval_active = True
        interval_strategy_equity *= 1.0 - final_cost
    close_interval()

    net_return = evaluation.robustness_base._compounded(daily_returns)
    cash_return = evaluation.robustness_base._compounded(cash_daily)
    return EnsembleSimulation(
        net_return=net_return,
        cash_return=cash_return,
        excess_return=net_return - cash_return,
        maximum_drawdown=evaluation.robustness_base._maximum_drawdown(
            daily_returns
        ),
        action_days=action_days,
        daily_returns=tuple(daily_returns),
        cash_daily_returns=tuple(cash_daily),
        interval_excess_contributions=tuple(interval_contributions),
        maximum_positive_interval_share=(
            evaluation.robustness_base._positive_concentration(
                interval_contributions
            )
        ),
    )


def _validate_v61(report: Mapping[str, Any]) -> str:
    payload = dict(report)
    claimed = str(payload.pop("report_sha256", ""))
    computed = hashlib.sha256(canonical_json(payload).encode("utf-8")).hexdigest()
    if claimed != computed:
        raise ParameterNeighborhoodV61Error(
            "v6.1 dependency report hash does not match contents"
        )
    if report.get("paper_only") is not True:
        raise ParameterNeighborhoodV61Error("v6.1 dependency is not paper-only")
    if report.get("authorizes_trading") is not False:
        raise ParameterNeighborhoodV61Error("v6.1 dependency authorizes trading")
    if report.get("status") != "ENSEMBLE_REJECTED":
        raise ParameterNeighborhoodV61Error("v6.1 rejection status changed")
    return claimed


def build_report(
    v312_report: Mapping[str, Any],
    v32_report: Mapping[str, Any],
    v603_report: Mapping[str, Any],
    v61_report: Mapping[str, Any],
) -> dict[str, Any]:
    v61_digest = _validate_v61(v61_report)
    if not PROTOCOL_PATH.is_file():
        raise ParameterNeighborhoodV61Error("v6.2 protocol is missing")

    original_simulator = evaluation.simulate_ensemble
    original_protocol = evaluation.PROTOCOL_PATH
    original_trial_count = evaluation.TRIAL_COUNT
    evaluation.simulate_ensemble = simulate_ensemble
    evaluation.PROTOCOL_PATH = PROTOCOL_PATH
    evaluation.TRIAL_COUNT = TRIAL_COUNT
    try:
        report = evaluation.build_report(v312_report, v32_report, v603_report)
    finally:
        evaluation.simulate_ensemble = original_simulator
        evaluation.PROTOCOL_PATH = original_protocol
        evaluation.TRIAL_COUNT = original_trial_count

    report.pop("report_sha256", None)
    report["schema_version"] = SCHEMA_VERSION
    report["v61_dependency_sha256"] = v61_digest
    report["preserves_v61_rejection"] = True
    report["status"] = (
        "RETROSPECTIVE_CONSENSUS_CANDIDATE_FORWARD_REQUIRED"
        if all(report["material_gates"].values())
        and all(report["statistical_gates"].values())
        else "CONSENSUS_ENSEMBLE_REJECTED"
    )
    report["historical_breakthrough"] = False
    report["forward_breakthrough"] = False
    report["report_sha256"] = hashlib.sha256(
        canonical_json(report).encode("utf-8")
    ).hexdigest()
    return report


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Run v6.2 parameter-free consensus ensemble"
    )
    parser.add_argument("--v312-json", type=Path, required=True)
    parser.add_argument("--v32-json", type=Path, required=True)
    parser.add_argument("--v603-json", type=Path, required=True)
    parser.add_argument("--v61-json", type=Path, required=True)
    parser.add_argument("--json-out", type=Path, required=True)
    args = parser.parse_args(argv)
    report = build_report(
        json.loads(args.v312_json.read_text(encoding="utf-8")),
        json.loads(args.v32_json.read_text(encoding="utf-8")),
        json.loads(args.v603_json.read_text(encoding="utf-8")),
        json.loads(args.v61_json.read_text(encoding="utf-8")),
    )
    args.json_out.parent.mkdir(parents=True, exist_ok=True)
    args.json_out.write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(
        json.dumps(
            {
                "status": report["status"],
                "conservative": report["conservative"],
                "material_gates": report["material_gates"],
                "statistical_gates": report["statistical_gates"],
                "bootstrap": report["source_specific_bootstrap"],
                "deflated_sharpe": report["deflated_sharpe"],
                "rank_stability": report["rank_stability"],
                "report_sha256": report["report_sha256"],
            },
            indent=2,
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
