from __future__ import annotations

from datetime import datetime, timedelta
from typing import Any, Mapping

from tradebot.research import parameter_neighborhood_ensemble_v61 as base


ParameterNeighborhoodV61Error = base.ParameterNeighborhoodV61Error
MemberState = base.MemberState
EnsembleSimulation = base.EnsembleSimulation
MEMBERS = base.MEMBERS
v31 = base.v31
_conservative = base._conservative


def simulate_ensemble(
    bars: Mapping[str, Mapping[datetime, Any]],
    features: Mapping[datetime, Mapping[str, base.v31.Features]],
    cash_returns: Mapping[datetime, float],
    start: datetime,
    end: datetime,
    cost: float,
    *,
    signal_lag_days: int,
) -> EnsembleSimulation:
    """Run the fixed ensemble without off-cadence normalization.

    New member targets remain capped at 10%. Naturally drifted member and
    aggregate weights are carried between genuine member decisions. The real
    aggregate portfolio is re-targeted only when at least one shadow member
    reaches a scheduled decision or exits to cash.
    """
    if len(MEMBERS) != 16:
        raise ParameterNeighborhoodV61Error(
            "frozen ensemble must contain 16 members"
        )
    if signal_lag_days < 1:
        raise ParameterNeighborhoodV61Error(
            "signal lag must be at least one day"
        )

    states = {model.model_id: MemberState() for model in MEMBERS}
    ensemble_weights: dict[str, float] = {}
    daily_returns: list[float] = []
    cash_daily: list[float] = []
    action_days = 0
    interval_active = False
    interval_strategy_equity = 1.0
    interval_cash_equity = 1.0
    interval_contributions: list[float] = []

    def close_interval() -> None:
        nonlocal interval_active, interval_strategy_equity, interval_cash_equity
        if interval_active:
            interval_contributions.append(
                (interval_strategy_equity - 1.0)
                - (interval_cash_equity - 1.0)
            )
        interval_active = False
        interval_strategy_equity = 1.0
        interval_cash_equity = 1.0

    day = start
    while day <= end:
        signal_day = day - timedelta(days=signal_lag_days)
        next_day = day + timedelta(days=1)
        if signal_day not in features:
            raise ParameterNeighborhoodV61Error(
                f"features unavailable for {base.v31._utc(signal_day)}"
            )
        cash_return = float(cash_returns[day])
        member_targets: dict[str, dict[str, float]] = {}
        pending_states: dict[str, MemberState] = {}
        any_member_decision = False

        for model in MEMBERS:
            state = states[model.model_id]
            target, selected, sleeve, age, trade_decision = base._member_target(
                model, state, features[signal_day]
            )
            exposure = sum(target.values())
            if trade_decision and exposure > model.maximum_exposure + 1e-12:
                raise ParameterNeighborhoodV61Error(
                    f"new member target cap violated by {model.model_id}"
                )
            if exposure < -1e-12 or exposure >= 1.0:
                raise ParameterNeighborhoodV61Error(
                    f"invalid naturally drifted member exposure for {model.model_id}"
                )
            turnover = sum(
                abs(
                    target.get(asset, 0.0)
                    - state.current_weights.get(asset, 0.0)
                )
                for asset in base.v31.ASSETS
            )
            if not trade_decision and turnover > 1e-12:
                raise ParameterNeighborhoodV61Error(
                    f"non-due turnover generated by {model.model_id}"
                )
            any_member_decision = any_member_decision or trade_decision
            member_cost = 0.5 * cost * turnover
            pending_states[model.model_id] = MemberState(
                current_weights=base._drift_weights(
                    target, bars, day, next_day, cash_return, member_cost
                ),
                selected_assets=selected,
                sleeve=sleeve,
                age=age,
            )
            member_targets[model.model_id] = target

        if any_member_decision:
            target = {
                asset: sum(
                    member_targets[model.model_id].get(asset, 0.0)
                    for model in MEMBERS
                )
                / len(MEMBERS)
                for asset in base.v31.ASSETS
            }
            target = {
                asset: weight
                for asset, weight in target.items()
                if weight > 1e-15
            }
        else:
            target = dict(ensemble_weights)

        exposure = sum(target.values())
        if exposure < -1e-12 or exposure >= 1.0:
            raise ParameterNeighborhoodV61Error(
                "invalid naturally drifted ensemble exposure"
            )
        turnover = sum(
            abs(
                target.get(asset, 0.0)
                - ensemble_weights.get(asset, 0.0)
            )
            for asset in base.v31.ASSETS
        )
        if not any_member_decision and turnover > 1e-12:
            raise ParameterNeighborhoodV61Error(
                "ensemble generated hidden off-cadence turnover"
            )
        trading_cost = 0.5 * cost * turnover
        action = turnover > 1e-10
        if action:
            close_interval()
            interval_active = True
            action_days += 1

        cash_weight = 1.0 - exposure
        crypto_return = sum(
            weight
            * (
                bars[asset][next_day].open / bars[asset][day].open
                - 1.0
            )
            for asset, weight in target.items()
        )
        net = cash_weight * cash_return + crypto_return - trading_cost
        daily_returns.append(net)
        cash_daily.append(cash_return)
        if interval_active:
            interval_strategy_equity *= 1.0 + net
            interval_cash_equity *= 1.0 + cash_return
        ensemble_weights = base._drift_weights(
            target, bars, day, next_day, cash_return, trading_cost
        )
        states = pending_states
        day += timedelta(days=1)

    final_turnover = sum(ensemble_weights.values())
    if final_turnover > 1e-12:
        final_cost = 0.5 * cost * final_turnover
        daily_returns.append(-final_cost)
        cash_daily.append(0.0)
        action_days += 1
        if not interval_active:
            interval_active = True
        interval_strategy_equity *= 1.0 - final_cost
    close_interval()

    net_return = base.robustness_base._compounded(daily_returns)
    cash_return = base.robustness_base._compounded(cash_daily)
    return EnsembleSimulation(
        net_return=net_return,
        cash_return=cash_return,
        excess_return=net_return - cash_return,
        maximum_drawdown=base.robustness_base._maximum_drawdown(
            daily_returns
        ),
        action_days=action_days,
        daily_returns=tuple(daily_returns),
        cash_daily_returns=tuple(cash_daily),
        interval_excess_contributions=tuple(interval_contributions),
        maximum_positive_interval_share=(
            base.robustness_base._positive_concentration(
                interval_contributions
            )
        ),
    )


# All existing evaluation, bootstrap, DSR and reporting functions resolve the
# module-global simulator at call time. Replace it before delegating to them.
base.simulate_ensemble = simulate_ensemble


def build_report(*args: Any, **kwargs: Any) -> dict[str, Any]:
    return base.build_report(*args, **kwargs)


def main(argv: list[str] | None = None) -> int:
    return base.main(argv)


if __name__ == "__main__":
    raise SystemExit(main())
